// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AuthCodeUser(ctx context.Context, arg AuthCodeUserParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
